### ISSUE TITLE
Back-End Refactoring ( Urls are Modified, FooDa App was divided )

### ISSUE THREAD

**Issue by JEOO2327** [swpp201901-team06/swpp-project#34]
- Back-End code Refactoring
  - FooDa App divide ( new Apps are added )
    - FooDa => Account, Archive, Ranking, Restaurant, Review, Tag

  - Urls are Modified
    - almost every Urls are modified 
    - details are written in "Back End Url List"

**Comment by lionminhu** [comment]
Need to refactor backend links in sagas files in the frontend accordingly
