### ISSUE TITLE
유저 랭킹 조작 방지 방법

### ISSUE THREAD

**Issue by JEOO2327** [swpp201901-team06/swpp-project#45]
- 문제점
  - 유저 랭킹의 경우 광고 목적으로 조작을 할 가능성이 있다.
- 해결방안
  - 방법1 :  유저 인증 기능을 추가한다. 이메일의 경우 여러 이메일로 다중 계정을 생성할 수 있으므로 휴대폰 인증 방식을 이용하자.
  - 방법2 : 앞에서도 다루었지만 랭킹 시스템이 아닌 추천 시스템으로 변경하면 다중 계정으로 광고를 하기 힘들 것이다.

**Comment by JEOO2327** [comment]
방법2 역시 악용될 우려가 있으므로 휴대폰 인증기능을  넣는것이 안전할 것으로 생각한다.

**Comment by lionminhu** [comment]
휴대폰 인증기능 역시 한 사람이 여러 폰(예를 들어, 가족의 폰)으로 여러 계정을 만들 수 있고, 가상 휴대폰 번호까지 이용하는 것까지 막을 수는 없다.
이 쯤에서 생각해야 하는 것은 조작을 어디까지 방지할지, 그리고 그에 대해 얼마나 시간을 소비할지이다. 어차피 완벽히 막을 수 없고, 완벽히 막으려고 할 수록 우리가 정말로 구현해야 하는 주 사이트 기능에 시간을 못 들이지 않을까 우려된다.

**Comment by lionminhu** [comment]
게다가 휴대폰 인증 방법을 시험하는데는 돈이 들 것으로 생각하는데, 테스팅하는 데에만 몇 천 원 이상 나가지 않을지 싶다. 이 프로젝트에 금전이 요구될 계획은 없었다.

**Comment by JEOO2327** [comment]
휴대폰은 이메일에 비해 여러개를 가지는 방법이 쉽지가 않다고 생각함. 그렇기 때문에 범죄에 악용할 때에도 타인의 명의를 불법으로 도용해서 대포폰 같은걸 만든다고 생각함. 휴대폰 인증의 경우 다른 팀에서 이미 구현하였고 api를 이용하는 것으로 생각보다 쉽게 할 수 있고, 기본으로 10통이 제공되며 부족할 것 같으면 한 사람당 1000원씩만 모아도 130통정도 테스트 할 수 있음. 애초에 마지막에 추가할 것이고, 다른 일을 위한 테스트 계정에서는 인증을 안 하도록 하면 문자를 많이 사용하지 않을것으로 예상됨.

**Comment by lionminhu** [comment]
(이런 경우가 일어나지 않는 게 상책이겠지만) 예를 들어 frontend 구현 중 버그가 생겨서 infinite loop가 발생하면, 휴대폰 인증 메시지 요청이 수백, 수천 개가 보내지지 않을지 걱정된다. 일정 시간동안 보낼 수 있는 인증 메시지를 제한시키도록 할 수 있나? 그것을 비교적 쉽게 구현할 수 있도록 하는 library가 있나?

만약 있다면 큰 문제는 없어보임.

**Comment by theNocturni** [comment]
1 2 번 둘다 적용하는것이 좋을거 같지만 시간/난이도 등이 걸림돌이 될 수 있으므로 1번을 우선순위로 두는것이 좋아보임

다만 민후 말대로 무한루프가 일어나지 않게 방지할 수 있어야 할듯함

**Comment by JEOO2327** [comment]
찾아본 결과 이메일 인증보다 휴대폰인증이 훨씬 구현하기 쉬움. 시간/난이도를 생각할거면 방법 1이 아니라 방법 2를 우선순위로 두어야 하고, 애초에 반복문 사용 자체를 안하는데 무한 루프를 돌릴 일을 걱정하는 것은 쓸데없는 걱정이지 않나 싶음.

정 걱정되면 백엔드에서 여러번 호출 못하도록 lock을 걸 수도 있으니까 괜찮을 것 같음.

**Comment by theNocturni** [comment]
시간/난이도 생각하면 방법 1이 아니라 2를 우선순위로 둬야 된다는 말은
추천 시스템이 휴대폰 인증보다 간단하다는 뜻?

반복문 사용이랑은 관계가 없는게 프론트쪽에서 에러가 일어날경우 무한 호출이 일어날 수 있음(실제 경험사항) 

백엔드에서 호출제한이 가능하다면 상관없을듯

**Comment by JEOO2327** [comment]
지금 이 논의를 하는 이유는 이메일 인증이 생각보다 구현하기 어려우며, 구글 이메일 외의 다른 이메일 인증은 구현하기 힘들 것 같아서 대안을 찾기 위한 것임.

정리하자면 
1. 구글 이메일 인증 기능만 추가하고 휴대폰 인증은 구현하지 말자.
2. 이메일인증을 구현하지 말고, 휴대폰 인증만 구현하자.

난이도는 2번이 더 쉽고 더 완벽하게 한 사람당 한 개의 계정을 만드는 것을 보장할 수 있음.
1번의 경우 물론 악용 가능성이 있지만 구글 이메일만 인증 한다면 구글 계정은 많이 생성할 수는 없으므로 악용될 우려는 적음. 다만 문제점은 구글 이메일을 가지고 있지 않은 사람은 가입이 불가능 한데, 이럴거면 차라리 구글 소셜 로그인 기능을 쓰는게 나음

**Comment by JEOO2327** [comment]
추천 시스템과는 별개로 이메일 인증 시스템 보다 휴대폰 인증 시스템이 더 만들기 간단함
무한 호출을 해결할 방법이 있는지 찾아보거나, 모든 시스템이 안정화 되었을때 휴대폰 인증을 넣으면 안전 할 것이라 생각함

**Comment by theNocturni** [comment]
아아
본문에 방법 1-인증
2-추천으로 되어있어서 그걸 말한거였음

구글 이메일보단 휴대폰 인증이 낫다고 생각함
그러므로 휴대폰 인증 관해선 이의 없음

**Comment by lionminhu** [comment]
휴대폰 인증 방식으로 진행하는 것에 동의.

**Comment by JEOO2327** [comment]
내가 본문 내용을 잘못 읽고 쓴듯, 아무튼 휴대폰 인증으로 진행하면서 무한 호출 같은 것을 방지하기 위한 기능을 추가하도록 하겠음.
