### ISSUE TITLE
현재 branch들 요약 및 정리

### ISSUE THREAD

**Issue by lionminhu** [swpp201901-team06/swpp-project#47]
현재 남아있는 branch들과 (내가 이해한 바) 그들의 목적은 아래와 같다.
- ~~`FD_present`: 중간 발표에 이용할 branch. 결국 `master`를 사용했던 것으로 기억한다.~~
- `JH_backend`: @JEOO2327의 backend branch.
- `MW_Docs`: Docs가 바뀔 때마다 여기서 업데이트해서 `master`로 PR을 올린다.
- ~~`MW_SignInPage`: 2nd iteration 당시 `SignInPage` 구현할 때 이용하던 branch. 이젠 삭제해도 되지 않을까 싶다.~~
- `MW_frontend_test`: frontend의 test를 짜기 위한 branch.
- ~~`SW_ArchivePage`: 나와 @theNocturni가 `ArchivePage`에 동시작업하기로 결정하기 전에 @theNocturni가 이용했던 branch. 삭제해도 될 것 같다.~~
- ~~`SW_SignUpPage_Test`: 2nd iteration 때 @theNocturni가 짜던 `SignUpPage`의 test. 삭제해도 될 것 같다.~~
- ~~`SW_SignUpPage`: 2nd iteration 때 @theNocturni가 짜던 `SignUpPage`. 삭제해도 될 것 같다.~~
- `frontend-combined`: 2nd iteration 때 `SignUpPage`, `SignInPage`, 그리고 `MainPage`를 `master`에 한꺼번에 merge하지 않고 대신 `frontend-combined`에서 제대로 돌아가는지 확인하려고 만듬. 이젠 필요 없어보이는데, 확실하진 않다. 그냥 `master`에 merge해도 되지 않을까 싶다.
- ~~`frontend_ArchivePage`: 3rd iteration 때 @theNocturni와 내가 `ArchivePage`와 기타 버그수정 작업을 동시에 진행하던 branch.~~
- `master`: `master`.
- `sh_design`: @MoBeau가 디자인을 맡던 branch. 다만 이것과 `sh_designsource` 간의 차이는 무엇인지 물어봐야함.
- ~~`sh_designsource`: @MoBeau의 디자인 작업 branch.~~
- ~~`sh_mainpage`: 2nd iteration때 @MoBeau가 `MainPage`를 구현하던 branch. 삭제해도 될 것 같다.~~
- ~~`MW_frontend_debug`: 3rd iteration 및 발표까지 터지던 버그들(https://github.com/swpp201901-team06/swpp-project/issues/40) 을 고치는 작업을 진행함.~~
- `MW_refactoring`: Refactoring code and improving features for functionalities already implemented.

내가 잘못 이해하거나, 내가 잘 모르는 branch에 대한 부분은 이 메시지를 수정해서 고쳐주기 바람. 삭제해도 되는 branch는 삭제해주고 해당되는 branch에 취소선 그어주기 바람.

또한, 새로 branch를 만든다면 여기에 그것에 대한 정보를 comment로 달아주기 바람.

**Comment by theNocturni** [comment]
발표할때 FD_present 사용했고 master에 없는 추가 수정사항들이 존재하기에 FD_present 에서 마스터로 merge가 필요함

**Comment by lionminhu** [comment]
`MW_SignInPage`, `SW_ArchivePage`, `SW_SignUpPage_Test`, `SW_SignUpPage`, `sh_mainpage` 삭제 완료. 기존 메시지에 반영함.

**Comment by MoBeau** [comment]
차이 없음 애초에 지금 다 master에 merge 한 상태라 sh_~~ branch들 다 없애도 됨

**Comment by lionminhu** [comment]
@MoBeau 그렇다면 다음 디자인 작업은 `sh_design` branch가 아니면 어느 branch에서 작업할 생각이지?

**Comment by MoBeau** [comment]
@lionminhu 그건 일단 component들 자리 잡기 전에 이미 만들어져 있는건 새로 master에서 pull해서 branch를 팔까 했음. 그냥 sh_design으로 해도 될듯 사실

**Comment by lionminhu** [comment]
그렇다면 `sh_design`에서 작업하기 전에 `master`에서 한 번 `pull`해서 업뎃된 버젼에서 작업하길 권장함.
일단 `sh_designsource`는 지움.

**Comment by lionminhu** [comment]
`MW_frontend_debug` branch 생성함.
`frontend_ArchivePage`는 더이상 공동작업이 이뤄지지 않으므로 지움.

**Comment by lionminhu** [comment]
Since `FD_present` and `MW_frontend_debug` branches have been merged, it seems to be okay to delete them.

**Comment by lionminhu** [comment]
Added `MW_refactoring` branch.
