### ISSUE TITLE
TypeError: response.json is not a function for getReviewList saga

### ISSUE THREAD

**Issue by lionminhu** [swpp201901-team06/swpp-project#52]
(I'll write in English since I can't type Korean on this computer without additional settings that I would not like to go through. If you want to say something, you can comment in Korean.)

I'm working on the bug 7 in this issue (https://github.com/swpp201901-team06/swpp-project/issues/40):
> 로그인되지 않은 상태(guest 상태)에서 다른 유저의 아카이브로 들어가도 public한 리뷰들이 안 뜸

Take a look at the below function:
https://github.com/swpp201901-team06/swpp-project/blob/06a170a24c7d36cd3a764aae5bd93a0edaf60f81/FD_frontend/src/store/ArchivePage/sagas.js#L10-L31

Upon loading archive page as guest, I found out that the `callUrl` request successfully returns a response that contains a review list object:
```
Array(2)
0:
archive: "test"
content: "content1"
eatWhen: "2000-01-01T01:01:01Z"
hits: 0
id: 1
photo: null
postTime: "2019-05-30T05:31:43.407475Z"
publicStatus: true
restaurantId: 1
score: 1
tags: "tag1"
__proto__: Object
1:
archive: "test"
content: "public content"
eatWhen: "2020-01-02T02:02:02Z"
hits: 0
id: 6
photo: "/photo/bordeaux-ans.bmp"
postTime: "2019-05-30T14:28:55.978211Z"
publicStatus: true
restaurantId: 1
score: 2
tags: "tag2"
__proto__: Object
length: 2
__proto__: Array(0)
```
But when I call `json` method on the response object as if it's a `Promise`, I get the following error message:
```
TypeError: response.json is not a function
    at getReviewList$ (sagas.js:10)
    at tryCatch (runtime.js:65)
    at Generator.invoke [as _invoke] (runtime.js:303)
    at Generator.prototype.<computed> [as next] (runtime.js:117)
    at next (proc.js:298)
    at Object.currCb [as cont] (proc.js:375)
    at end (proc.js:342)
    at Object.task.cont (proc.js:98)
    at next (proc.js:308)
    at currCb (proc.js:375)
```

It's strange though; don't other sagas use `json` method for `Promise` objects just fine?
Or is `response` simply not a `Promise` object in this case?
I'll look into some other sagas (in the other sagas files as well) that used the `json` method.

**Comment by lionminhu** [comment]
> It's strange though; don't other sagas use `json` method for `Promise` objects just fine?
We use the `json` method only in the sagas files for `ArchivePage` and `PostPage`.
However, the `getReviewList` saga works just fine when logged in, so what is the difference here, when not logged in?

**Comment by lionminhu** [comment]
> Or is `response` simply not a `Promise` object in this case?

Actually, printing the `response` gave us an `Array` of two review JSON objects, which I don't think is a `Promise` object.

Printing the `response` when logged in as `test@gmail.com` account gives us:
```
Response {type: "cors", url: "http://127.0.0.1:8000/Review/list/test/", redirected: false, status: 200, ok: true, …}
body: (...)
bodyUsed: true
headers: Headers {}
ok: true
redirected: false
status: 200
statusText: "OK"
type: "cors"
url: "http://127.0.0.1:8000/Review/list/test/"
__proto__: Response
```
This is clearly different.

**Comment by lionminhu** [comment]
Here is the implementation for `callUrl` (don't mind the `console.log`s):
https://github.com/swpp201901-team06/swpp-project/blob/06a170a24c7d36cd3a764aae5bd93a0edaf60f81/FD_frontend/src/store/sagas.js#L6-L68

Note that when one is not logged in, the requests are passed by calling `api.post`, `api.get`, etc.
My hypothesis is that `api.post`, `api.get`, and other methods from `services/api` return a response that has already been converted to JSON objects, rather than raw `Promise` objects.

I can change the behaviour of `callUrl` such that it returns a converted JSON objects for responses when logged in as well, but I'm afraid that this may require modification to other sagas that depend on `callUrl`.

An alternative is to keep in mind that `callUrl` will return JSON when not logged in, and implement the sagas accordingly. However, this will make the implementation `callUrl` quite unintuitive at hindsight.

@theNocturni I should ask for your advice. Which would you prefer?

**Comment by theNocturni** [comment]
Api를 직접 수정하는건 어떰?

**Comment by lionminhu** [comment]
>Api를 직접 수정하는건 어떰?
어차피 api도 src 내부의 폴더일 뿐이라
수정해도 상관없을듯

그럴 생각으로 한 번 `services/api/index.js` 한 번 들여다 봤는데, 솔직히 코드가 이해가 안 가서 수정하긴 어려울 듯

>아니면 로그인 안되어있을때 Promise를 리턴하게 하는건?

Credentials가 없는 상태에서 backend에 request를 보내는 건 어떻게 하는 건지 찾아봐야 가능함. 불가능할 것 같지는 않음.

**Comment by theNocturni** [comment]
로그인 안된상태에서 Promise가 어렵다면

Consistency를 위해 로그인 된 상태에서 JSON이 좋을듯

**Comment by lionminhu** [comment]
> I can change the behaviour of `callUrl` such that it returns a converted JSON objects for responses when logged in as well, but I'm afraid that this may require modification to other sagas that depend on `callUrl`.

그렇다면 이걸로 반영해 봐야겠다. 새로운 버그 터질 것을 우려하긴 하지만 일단은 해봄.

**Comment by JEOO2327** [comment]
백엔드쪽에서 request.user가 존재한다는 가정하에 코드를 작성했는데, 이거때문이려나
if request.user == user이 부분이 문제가 될 수도 있을 것 같은데 한번 수정해볼게

```python
class ReviewListView(APIView):
    def get(self, request, username) :
        user = CustomUser.objects.select_related('Archive').get(username = username)
        #get_object_or_404(CustomUser, username = username)
        #.select_related('Archive')
        archive = get_object_or_404(Archive, user = user)
        if request.user == user:
                queryset = archive.review_archive.all().order_by(archive.sortOption)
                serializer_class = serializers.ReviewSerializer(queryset, many = True)
                return Response(serializer_class.data)

        queryset = archive.review_archive.filter(publicStatus = True).order_by(archive.sortOption)
        serializer_class = serializers.ReviewSerializer(queryset, many = True)
        return Response(serializer_class.data)
```

**Comment by lionminhu** [comment]
백엔드 쪽 문제일 것 같지는 않아, 당장 `class ReviewListView` 코드에도 두 경우 모두 `Response`를 보내주긴 하니까.
그냥 `arc`가 API call하고 받은 response를 `services/api/index.js`에서 알아서 처리해서 넘겨주기 때문이라 생각하고 있어.

**Comment by theNocturni** [comment]
api에 보면 response를 fetch 하고 checkStatus하고 parseJSON을 하는데 이게 response=>response.json() 함수라서

백엔드에서 어떻게 되건 일단 프론트쪽에선 json을 받아야됨
아마 checkStatus에서 문제가 생겨서 parseJSON이 되기 전에 오류가 뜬게 아닐까 생각함

**Comment by lionminhu** [comment]
I've just noticed `parseJSON`, as you've mentioned:
https://github.com/swpp201901-team06/swpp-project/blob/06a170a24c7d36cd3a764aae5bd93a0edaf60f81/FD_frontend/src/services/api/index.js#L15

and the usage of `parseJSON`:
https://github.com/swpp201901-team06/swpp-project/blob/06a170a24c7d36cd3a764aae5bd93a0edaf60f81/FD_frontend/src/services/api/index.js#L40-L43

The error occurred because `callUrl` returned JSON data rather than a promise, on which I then tried to call `.json` method.

I'm hoping that simply not calling `parseJSON` would fix the problem.

**Comment by lionminhu** [comment]
As of this commit (https://github.com/swpp201901-team06/swpp-project/commit/1c3609c51d4913e57205a39e48aff864ae5e2f89), `callUrl` has been fixed to return JSON data of promise, and all the calls to `callUrl` have been fixed too.

Lastly, before I close this issue, I would like to ask @theNocturni for the purpose of checking for response status code 404 here (in the code before I made the fix):
https://github.com/swpp201901-team06/swpp-project/blob/06a170a24c7d36cd3a764aae5bd93a0edaf60f81/FD_frontend/src/store/ArchivePage/sagas.js#L17-L26

**Comment by lionminhu** [comment]
로그아웃한 상태에서 public한 리뷰리스트 띄우는 건 일단 잘 되는 듯
![image](https://user-images.githubusercontent.com/17691594/58699512-a3746680-83d8-11e9-92eb-ef630619fa43.png)

**Comment by lionminhu** [comment]
아, 잊기 전에 말해두는데, 버그 고치면서 깨달은 것이 있는데, `.json` method는 pure function이 아닌 것 같아.
즉, `yield response.json()` 한 번 하면 `response` 자체가 response로 바뀌어버리는 듯해.
`yield response.json()` 한 번 한 상태에서 또 다시 `yield response.json()`을 call하면 JSON인 `response`에서 `.json`이란 method를 호출하려는 게 되므로 `not a function`이란 에러가 뜨는 것이라고 이해하고 있어.

**Comment by lionminhu** [comment]
After talking with @theNocturni (outside of Github), I'm guessing that it was because of archive list not `POST`-ing upon account sign up or because of some authentication error.
As none of those problems are occurring right now, I've commented out the portion that checks for 404 error.
