### ISSUE TITLE
백엔드에서의 Response Type을 JSON으로 통합시키기

### ISSUE THREAD

**Issue by JEOO2327** [swpp201901-team06/swpp-project#53]
- JSON이란? (내가 이해한 내용인데 정확한지는 모르겠지만 일단 참고용)
JSON은 서로 다른 언어들끼리 (예를 들어 파이썬과 자바스크립트) 자료를 주고 받기 위해 사용하는 프로토콜이다. 각 언어들은 자료형들을(배열, 딕셔너리 등등) 저장하는 방법이 서로 달라서 이를 byte값 그대로 전송하면 전송받은 언어에서는 이를 해석하지 못한다. 이러한 문제를 해결하고자 만들어진 것이 JSON이다. JSON은 각 언어들마다 변환하는 방법과 JSON 타입을 해석하는 방법이 존재한다. 따라서 이를 이용하면 자료형을 유지시키며 다른 언어로 만들어진 서버로 값을 전송 할 수 있다.
 예를들어 파이썬에서 자바스크립트로 데이터를 전송할 때 JSON으로 변환시켜서 보내기로 약속을 하는 것이다. 그러면 자바스크립트 쪽에서는 전달받은 데이터를 JSON.parse() 같은 함수로 해석해서 전달된 값을 사용할 수 있다. 

- 문제점
현재 백엔드에서는 Response 함수를 통해 응답하고 있는데, 이게 JSON으로 리턴이 되는것인지 확신이 없다. 웹 페이지나 postMan을 이용해서 확인했을 때는 JSON으로 나오긴 하는데 generic view로 구현해놔서 알아서 JSON으로 return이 되는 것인지, serializer 때문에 JSON으로 되는 것인지 잘 모르겠음. 민후가 말한 비로그인 상태시 리뷰 리스트를 제대로 가져오지 못하는 버그에서 뭔가 타입이 이상하게 보내지는 것 같던데, 다른 url에서도 이런일이 생기는지 확인하고 싶어.

- 요구사항
현재 front-end쪽에서는 url을 호출했을때 어떤 형식으로 값이 나오는지 혹시 알고 있으면 comment로 알려주길 바람. 각각의 url마다 다른 타입으로 값이 나오는지, 아니면 모두 JSON으로 나오는지 알고 싶음.

**Comment by lionminhu** [comment]
> 현재 front-end쪽에서는 url을 호출했을때 어떤 형식으로 값이 나오는지 혹시 알고 있으면 comment로 알려주길 바람. 각각의 url마다 다른 타입으로 값이 나오는지, 아니면 모두 JSON으로 나오는지 알고 싶음.

backend URL을 모두 체크해보진 않았지만, 일단 내가 체크해본 URL 호출 결과(get review list, get review detail, post review, delete review)는 모두 아래와 같은 Response 형식으로 나오고 있음.
![image](https://user-images.githubusercontent.com/17691594/58700766-f3086180-83db-11e9-8d9f-348679233e55.png)
이제 이 object에다가 `.json()` method를 call하면 JSON으로 변환이 됨.

> 민후가 말한 비로그인 상태시 리뷰 리스트를 제대로 가져오지 못하는 버그에서 뭔가 타입이 이상하게 보내지는 것 같던데, 다른 url에서도 이런일이 생기는지 확인하고 싶어.

여기(https://github.com/swpp201901-team06/swpp-project/issues/52#issuecomment-497646648) 에서도 말했지만 역시 backend 문제는 아니라고 봄. backend는 그냥 위와 같은 Response 형식으로 일관성 있게 보내주기 부탁. Backend에서 따로 JSON으로 변환해주진 않았으면 좋겠음.
