### ISSUE TITLE
sign in page 에서 버그 발견

### ISSUE THREAD

**Issue by MoBeau** [swpp201901-team06/swpp-project#61]
sign in에 실패해서 sign in failed가 뜨고 나면 sign up page로 넘어가는 버튼이 작동하지 않음. 클릭만 되고 url 전환이 안됨.

**Comment by theNocturni** [comment]
수정했음, 곧 push할것

**Comment by lionminhu** [comment]
수웅이 이 PR(https://github.com/swpp201901-team06/swpp-project/pull/63) 에서 고친 것으로 이해함.

**Comment by theNocturni** [comment]
민후 말대로 수정했으므로 close하겠음
