### ISSUE TITLE
archive page bug 발견

### ISSUE THREAD

**Issue by MoBeau** [swpp201901-team06/swpp-project#67]
아무 리뷰도 없는 상태인데 Score 라는 text가 떠있고 클릭하면 뭔가 리뷰 리스트 마냥 글자가 펼쳐짐. 리뷰가 아예 없는 경우에는 No Review 같은 별도의 text를 띄워주는게 좋지 않을까 생각

**Comment by lionminhu** [comment]
이미 로그인한 상태를 말하는 건가
Review의 score는 어느 특정 review가 선택돼서 ReviewDetail로 나오는 경우일텐데, 혹시 그 쪽 문제인가

혹시 스샷 찍을 수 있으면 올려주기 부탁

**Comment by theNocturni** [comment]
그거 정렬기준임

**Comment by lionminhu** [comment]
Dropdown과는 다르게 생긴 건가

>클릭하면 뭔가 리뷰 리스트 마냥 글자가 펼쳐짐

그렇다면 이건 뭐지, 그냥 sort option들 나열한 건가

**Comment by theNocturni** [comment]
yes
Dropdown 맞고 dropdown처럼 안보이는 이유는...react-dropdown에서 기본적으로 ui를 제공하는데 그게 이상하게 import 하면 오류 띄워서 인터페이스 못넣은거

**Comment by MoBeau** [comment]
아하 오류인줄...
